var drawings = [
	{
		"name": "Huanhuan",
    "color":"blue",
    "pics": "<img class='people' src='images/boy.png'>",
    "size": 62,
		"mood": 7,
		"smile":"yes",
	},
	{
		"name":"Doudou",
    "pics": "<img class='people' src='images/girl1.png'>",
    "color":"pink",
    "size": 55,
		"mood": 10,
		"smile":"yes",
	},
	{
		"name":"Jiajia",
    "pics": "<img class='people' src='images/girl2.png'>",
    "size": 54,
		"mood": 3,
		"smile":"yes",
	},
	{
		"name":"Tiantian",
    "pics": "<img class='people' src='images/girl3.png'>",
    "size": 36,
		"mood": 3,
		"smile":"yes",
	},
	{
		"name":"Xuanxuan",
    "pics": "<img class='people' src='images/girl4.png'>",
    "size": 35,
		"mood": 8,
  },
  {
    "name":"Beibei",
    "pics": "<img class='people' src='images/girl5.png'>",
    "size": 51,
		"mood": 3,
  },
  {
    "name":"Qiqi",
    "pics": "<img class='people' src='images/girl6.png'>",
    "size": 65,
		"mood": 3,
  },
  {
    "name":"Yueyue",
    "pics": "<img class='people' src='images/girl7.png'>",
    "size": 58,
		"mood": 9,
  },
  {
    "name":"Shanshan",
    "pics": "<img class='people' src='images/girl8.png'>",
    "size": 56,
		"mood": 3,
  },
  {
    "name":"Tongtong",
    "pics": "<img class='people' src='images/girl9.png'>",
    "size": 60,
		"mood": 3,
  },
  {
    "name":"Xixi",
    "pics": "<img class='people' src='images/girl10.png'>",
    "size": 59,
		"mood": 3,
  },
  {
    "name":"Sisi",
    "pics": "<img class='people' src='images/girl11.png'>",
    "size": 14,
		"mood": 3,
  },
  {
    "name":"Feifei",
    "pics": "<img class='people' src='images/girl12.png'>",
    "genre":"Synth Pop",
    "size": 1,
		"mood": 3,
  },
  {
    "name":"Nuonuo",
    "pics": "<img class='people' src='images/girl13.png'>",
    "size": 30,
		"mood": 3,
  },
  {
    "name":"Wenwen",
    "pics": "<img class='people' src='images/girl14.png'>",
    "size": 34,
		"mood": 3,
  },
  {
    "name":"Xuexue",
    "pics": "<img class='people' src='images/girl15.png'>",
    "size": 67,
		"mood": 3,
  },
  {
    "name":"Honghong",
    "pics": "<img class='people' src='images/girl16.png'>",
    "size": 66,
		"mood": 3,
  },
  {
    "name":"Ningning",
    "pics": "<img class='people' src='images/girl17.png'>",
    "size": 68,
		"mood": 3,
  },
  {
    "name":"Yaoyao",
    "pics": "<img class='people' src='images/girl18.png'>",
    "size": 50,
		"mood": 3,
  },
  {
    "name":"Yanyan",
    "pics": "<img class='people' src='images/girl19.png'>",
    "size": 69,
		"mood": 3,
  },
  {
    "name":"Haohao",
    "pics": "<img class='people' src='images/girl20.png'>",
    "size": 61,
		"mood": 3,
  },
  {
    "name":"Xinxin",
    "pics": "<img class='people' src='images/girl21.png'>",
    "size": 2,
		"mood": 3,
  },
  {
    "name":"Yaya",
    "pics": "<img class='people' src='images/girl22.png'>",
    "size": 47,
		"mood": 3,
  },
	{
		"name":"Lulu",
		"pics": "<img class='people' src='images/girl23.png'>",
		"size": 57,
		"mood": 3,
	},
	{
		"name": "cake1",
    "color":"blue",
    "pics": "<img class='cakes' src='images/cake1.png'>",
    "size": 32,
		"mood": 3,
		"smile":"no",

	},
	{
		"name":"cake2",
    "pics": "<img class='cakes' src='images/cake2.png'>",
    "color":"pink",
    "size": 48,
		"mood": 3,
	},
  {
		"name":"cake3",
    "pics": "<img class='cakes' src='images/cake3.png'>",
    "color":"pink",
    "size": 45,
		"mood": 3,
	},
	{
  	"name": "feeling1",
    "color":"blue",
    "pics": "<img class='text' src='images/text1.png'>",
    "size": 13,
		"mood": 3,
  },
  {
  	"name":"feeling2",
    "pics": "<img class='text' src='images/text2.png'>",
    "size": 3,
    "color":"pink",
		"mood": 3,
  },
  {
  	"name":"feeling3",
    "pics": "<img class='text' src='images/text3.png'>",
    "color":"pink",
    "size": 4,
		"mood": 3,
  },
  {
    "name":"feeling4",
    "pics": "<img class='text' src='images/letter.png'>",
    "color":"pink",
    "size": 24,
		"mood": 3,
  },
  {
    "name":"myFlipPhone",
    "pics": "<img class='text' src='images/phone.png'>",
    "color":"pink",
    "size": 52,
		"mood": 3,
  },
  {
  	"name": "aButterfly",
    "color":"blue",
    "pics": "<img class='items' src='images/butterfly1.png'>",
    "size": 9,
		"mood": 6,
  },
	{
  	"name":"Bow1",
    "pics": "<img class='items' src='images/bow1.png'>",
    "color":"pink",
    "size": 12,
		"mood": 3,
  },
  {
  	"name":"Bow2",
    "pics": "<img class='items' src='images/bow2.png'>",
    "color":"pink",
    "size": 5,
		"mood": 3,
  },
  {
    "name":"mySandals",
    "pics": "<img class='items' src='images/shoes.png'>",
    "color":"pink",
    "size": 11,
		"mood": 3,
  },
  {
    "name":"myToybear",
    "pics": "<img class='items' src='images/toybear.png'>",
    "color":"pink",
		"size": 10,
		"mood": 3,
  },
  {
    "name":"myCat",
    "pics": "<img class='items' src='images/cat.png'>",
    "color":"pink",
		"size": 40,
		"mood": 3,
  },
  {
    "name":"myCarpet",
    "pics": "<img class='items' src='images/carpet.png'>",
    "color":"pink",
		"size": 46,
		"mood": 3,
  },
  {
    "name":"myDesknChair",
    "pics": "<img class='items' src='images/deskchair.png'>",
    "color":"pink",
		"size": 42,
		"mood": 3,
  },
  {
    "name":"myCloset",
    "pics": "<img class='items' src='images/closet.png'>",
    "color":"pink",
		"size": 63,
		"mood": 3,
  },
  {
    "name":"myWindow",
    "pics": "<img class='items' src='images/window.png'>",
    "color":"pink",
		"size": 44,
		"mood": 3,
  },
  {
    "name":"myLamp",
    "pics": "<img class='items' src='images/lamb.png'>",
    "color":"pink",
		"size": 15,
		"mood": 4,
  },
	{
		"name":"myBook",
		"pics": "<img class='items' src='images/book.png'>",
		"color":"pink",
		"size": 16,
		"mood": 4,
	},
	{
		"name":"myBalloons",
		"pics": "<img class='items' src='images/balloons.png'>",
		"color":"pink",
		"size": 64,
		"mood": 4,
	},
  {
  	"name": "cloud1",
    "color":"blue",
    "pics": "<img class='cloud' src='images/cloud1.png'>",
		"size": 18,
		"mood": 3,
	},
  {
    "name":"cloud2",
    "pics": "<img class='cloud' src='images/cloud2.png'>",
    "color":"pink",
		"size": 41,
		"mood": 3,
	},
  {
    "name":"sun1",
    "pics": "<img class='sun' src='images/sun2.png'>",
    "color":"pink",
		"size": 33,
		"mood": 3,
  },
  {
    "name":"sun2",
    "pics": "<img class='sun2' src='images/sun3.png'>",
    "color":"pink",
		"size": 72,
		"mood": 5,
  },
  {
    "name":"sun3",
    "pics": "<img class='sun' src='images/sun4.png'>",
    "color":"pink",
		"size": 25,
		"mood": 3,
  },
  {
    "name":"sun4",
    "pics": "<img class='sun' src='images/sun5.png'>",
    "color":"pink",
		"size": 22,
		"mood": 3,
  },
  {
    "name":"sun5",
    "pics": "<img class='sun5' src='images/sun6.png'>",
    "color":"pink",
		"size": 31,
		"mood": 3,
  },
  {
    "name": "house1",
    "color":"blue",
    "pics": "<img class='outside' src='images/house1.png'>",
		"size": 21,
		"mood": 2,
  },
  {
    "name":"house2",
    "pics": "<img class='outside' src='images/house2.png'>",
    "color":"pink",
		"size": 19,
		"mood": 1,
  },
  {
    "name":"house3",
    "pics": "<img class='outside' src='images/house3.png'>",
    "color":"pink",
		"size": 20,
		"mood": 3,
  },
  {
    "name":"grass",
    "pics": "<img class='outside' src='images/grass.png'>",
    "color":"pink",
		"size": 8,
		"mood": 3,
  },
  {
    "name":"mySwing",
    "pics": "<img class='swing' src='images/wing.png'>",
    "color":"pink",
		"size": 49,
		"mood": 3,
  },
  {
    "name": "tree1",
    "color":"blue",
    "pics": "<img class='tree' src='images/tree1.png'>",
		"size": 17,
		"mood": 3,
  },
  {
    "name":"tree2",
    "pics": "<img class='tree2' src='images/tree2.png'>",
    "color":"pink",
		"size": 73,
		"mood": 3,
  },
  {
    "name":"tree3",
    "pics": "<img class='tree' src='images/tree3.png'>",
    "color":"pink",
		"size": 43,
		"mood": 3,
  },
  {
    "name":"flower1",
    "pics": "<img class='flower' src='images/flower1.png'>",
    "color":"pink",
		"size": 39,
		"mood": 3,
  },
  {
    "name":"flower2",
    "pics": "<img class='flower' src='images/flower2.png'>",
    "color":"pink",
		"size": 38,
		"mood": 3,
  },
  {
    "name":"flower3",
    "pics": "<img class='flower' src='images/flower3.png'>",
    "color":"pink",
		"size": 37,
		"mood": 3,
  },
  {
    "name":"flower4",
    "pics": "<img class='flower' src='images/flower4.png'>",
    "color":"pink",
		"size": 7,
		"mood": 3,
  },
  {
    "name":"flower5",
    "pics": "<img class='flower' src='images/flower5.png'>",
    "color":"pink",
    "size": 23,
		"mood": 3,
  },
  {
    "name": "flower6",
    "color":"blue",
    "pics": "<img class='flower' src='images/flower6.png'>",
    "size": 26,
		"mood": 3,
  },
  {
    "name": "flower7",
    "color":"blue",
    "pics": "<img class='flower' src='images/flower7.png'>",
    "size": 27,
		"mood": 3,
  },
  {
    "name": "flower8",
    "color":"blue",
    "pics": "<img class='flower' src='images/flower8.png'>",
    "size": 28,
		"mood": 3,
  },
  {
    "name": "flower9",
    "color":"blue",
    "pics": "<img class='flower' src='images/flower9.png'>",
    "size": 29,
		"mood": 3,
  },
  {
    "name": "flower10",
    "color":"blue",
    "pics": "<img class='flower' src='images/flower10.png'>",
    "size": 6,
		"mood": 3,
  },
  {
    "name": "flower11",
    "color":"blue",
    "pics": "<img class='flower' src='images/flower11.png'>",
    "size": 70,
		"mood": 3,
  },
   {
    "name": "flower12",
    "color":"blue",
    "pics": "<img class='flower' src='images/flower12.png'>",
    "size": 71,
		"mood": 3,

},
{
    "name": "flower13",
    "color":"blue",
    "pics": "<img class='flower' src='images/flower13.png'>",
    "size": 53,
		"mood": 3,
}

]


for(var i=0; i<drawings.length; i++){
  var imageDiv = $('<div/>', {
      'class': 'image',
			id:drawings[i].name
    })
    .data('drawings', drawings[i])
    .html(drawings[i].pics)
	  .css({"position":"absolute","left":"100px"})
     $('#images').append(imageDiv)



  var buttonDiv = $('<button/>', {
      'class': 'button'
    })
    .data('drawings', drawings[i])
    .html(drawings[i].name)
    .click(function(){
    $( '#' + $(this).data('drawings').name).toggle();
    })
  $('#buttons').append(buttonDiv)
};
